User.new({ :email => 'admin@cheetahcms.com', :password => 'password', :first_name => 'Cheetah', :last_name => 'Admin'}).save
Footer.create("title"=>"Main Footer")
Footer.create("title"=>"Articles Footer")
HelpCategory.create("title"=>"Pages")
HelpCategory.create("title"=>"Sections")
HelpCategory.create("title"=>"Assets")
HelpCategory.create("title"=>"Publications")
HelpCategory.create("title"=>"Posts")
HelpCategory.create("title"=>"Comments")
HelpCategory.create("title"=>"Footers")
HelpCategory.create("title"=>"Forms")
HelpCategory.create("title"=>"Settings")
HelpCategory.create("title"=>"Users")
HelpCategory.create("title"=>"Design")
HelpCategory.create("title"=>"Navigation")
HelpCategory.create("title"=>"Sliders")
Help.create("help_category_id"=>2, "title"=>"Adding your own class.", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>1, "title"=>"Creating a new page", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>1, "title"=>"Editing a page", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>1, "title"=>"Publishing and page visibility", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>1, "title"=>"Choosing a footer ", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>4, "title"=>"New publication", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>10, "title"=>"New user", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>10, "title"=>"New Password", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>10, "title"=>"Invitation", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>10, "title"=>"Edit/Delete", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>10, "title"=>"User roles", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>7, "title"=>"New footer", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>7, "title"=>"Edit/Delete footer", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>7, "title"=>"Footer content", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>4, "title"=>"Edit/Delete publication", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>4, "title"=>"Publication settings", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>5, "title"=>"Edit/Delete Post", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>5, "title"=>"Post settings", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>5, "title"=>"Post Image", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>4, "title"=>"Sidebars and sidebar content", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>6, "title"=>"Approve/Remove content", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>6, "title"=>"Un-publish comment", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>11, "title"=>"Custom CSS", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>9, "title"=>"Edit Settings and Site logo image", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>8, "title"=>"Creating a new form", "video"=>"", "content"=>"Lorem ipsum dolor sit amet\\")
Help.create("help_category_id"=>13, "title"=>"Adding a slider", "video"=>"", "content"=>"<p>content&nbsp;</p>")
Help.create("help_category_id"=>13, "title"=>"Editing content", "video"=>"", "content"=>"<p>content</p>")
Help.create("help_category_id"=>12, "title"=>"How to change the order of pages", "video"=>"", "content"=>"content here")
Help.create("help_category_id"=>3, "title"=>"First post", "video"=>"6yvIkbStKSw", "content"=>"<p><span style=\"font-family: Arial, Helvetica, sans; line-height: 14px; text-align: justify;\">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as </span></p>\r\n<p><span style=\"font-family: Arial, Helvetica, sans; line-height: 14px; text-align: justify;\">necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc. UPdated test</span></p>")
FunctionName.create("category"=>"publications", "name"=>"Publication")
FunctionName.create("category"=>"social/RSS", "name"=>"Social Networks/RSS")
FunctionName.create("category"=>"navigation", "name"=>"Navigation Group")
FunctionName.create("category"=>"Information", "name"=>"Testimonials")
FunctionName.create("category"=>"Video", "name"=>"Youtube Videos")
FunctionName.create("category"=>"forms", "name"=>"Custom Forms")
FunctionName.create("category"=>"Information", "name"=>"Frequently Asked Questions")
FunctionName.create("category"=>"Information", "name"=>"Contact Information")
FunctionName.create("category"=>"Information", "name"=>"Shared Content")
FunctionName.create("category"=>"navigation", "name"=>"Navigation Branch")
FunctionName.create("category"=>"Assets", "name"=>"Images")
FunctionName.create("category"=>"Assets", "name"=>"Documents")
FunctionName.create("category"=>"Assets", "name"=>"Videos")
FunctionName.create("category"=>"Assets", "name"=>"Audios")
FunctionName.create("category"=>"Assets", "name"=>"Users")
FunctionName.create("category"=>"Assets", "name"=>"Links")
CssClasses.create("css_class"=>"float-left")
CssClasses.create("css_class"=>"float-right")
CssClasses.create("css_class"=>"clear-both")
CssClasses.create("css_class"=>"divider")
ImageSize.create("size"=>"Thumb", "size_value"=>"thumb")
ImageSize.create("size"=>"Small", "size_value"=>"small")
ImageSize.create("size"=>"Medium", "size_value"=>"medium")
ImageSize.create("size"=>"Large", "size_value"=>"large")
ImageSize.create("size"=>"Original", "size_value"=>"original")
Navigation.create("nav_group"=>"Primary", "description"=>"")
Navigation.create("nav_group"=>"Constant", "description"=>"I changed this")
Navigation.create("nav_group"=>"Errors", "description"=>"")
Network.create("name"=>"Blogger", "icon"=>"blogger.png", "share_code"=>"0")
Network.create("name"=>"Delicious", "icon"=>"delicious.png", "share_code"=>"http://del.icio.us/post?url=")
Network.create("name"=>"Design Bump", "icon"=>"design-bump.png", "share_code"=>"http://www.designbump.com/submit?url=")
Network.create("name"=>"Digg", "icon"=>"digg.png", "share_code"=>"http://digg.com/submit?phase=2&url=")
Network.create("name"=>"Facebook", "icon"=>"facebook.png", "share_code"=>"http://www.facebook.com/share.php?u=")
Network.create("name"=>"Feedburner", "icon"=>"feedburner.png", "share_code"=>"0")
Network.create("name"=>"Flickr", "icon"=>"flickr.png", "share_code"=>"0")
Network.create("name"=>"Forrst", "icon"=>"forrst.png", "share_code"=>"0")
Network.create("name"=>"Google", "icon"=>"google.png", "share_code"=>"http://www.google.com/bookmarks/mark?op=edit&bkmk=")
Network.create("name"=>"Linkedin", "icon"=>"linkedin.png", "share_code"=>"http://www.linkedin.com/shareArticle?mini=true&url=")
Network.create("name"=>"Meetup", "icon"=>"meetup.png", "share_code"=>"0")
Network.create("name"=>"Metacafe", "icon"=>"metacafe.png", "share_code"=>"0")
Network.create("name"=>"Mixx", "icon"=>"mixx.png", "share_code"=>"http://www.mixx.com/submit?page_url=")
Network.create("name"=>"Myspace", "icon"=>"myspace.png", "share_code"=>"http://www.myspace.com/Modules/PostTo/Pages/?u=\n")
Network.create("name"=>"Newsvine", "icon"=>"newsvine.png", "share_code"=>"http://www.newsvine.com/_tools/seed&save?u=")
Network.create("name"=>"Picasa", "icon"=>"picasa.png", "share_code"=>"0")
Network.create("name"=>"Reddit", "icon"=>"reddit.png", "share_code"=>"http://reddit.com/submit?url=")
Network.create("name"=>"Sharethis", "icon"=>"sharethis.png", "share_code"=>"0\n")
Network.create("name"=>"Slashdot", "icon"=>"slashdot.png", "share_code"=>"http://slashdot.org/bookmark.pl?title=Fullscreen%20Image%20Blur%20Effect%20with%20HTML5&url=")
Network.create("name"=>"Stack Overflow", "icon"=>"stackoverflow.png", "share_code"=>"0")
Network.create("name"=>"Stumbleupon", "icon"=>"stumbleupon.png", "share_code"=>"http://www.stumbleupon.com/submit?url=")
Network.create("name"=>"Technorati", "icon"=>"technorati.png", "share_code"=>"http://technorati.com/faves?add=")
Network.create("name"=>"Tumblr", "icon"=>"tumblr.png", "share_code"=>"http://www.tumblr.com/share?v=3&u=")
Network.create("name"=>"Twitter", "icon"=>"twitter.png", "share_code"=>"http://twitter.com/home?status=")
Network.create("name"=>"Vimeo", "icon"=>"vimeo.png", "share_code"=>"0")
Network.create("name"=>"WordPress", "icon"=>"wordpress-2.png", "share_code"=>"0")
Network.create("name"=>"Xing", "icon"=>"xing.png", "share_code"=>"https://www.xing.com/app/user?op=share&url=")
Network.create("name"=>"Yelp", "icon"=>"yelp.png", "share_code"=>"0")
Network.create("name"=>"YouTube", "icon"=>"youtube.png", "share_code"=>"0")
Network.create("name"=>"RSS", "icon"=>"rss.png", "share_code"=>"0")
Network.create("name"=>"Design Float", "icon"=>"designfloat.png", "share_code"=>"http://www.designfloat.com/submit.php?url=")
Network.create("name"=>"pinterest", "icon"=>"pinterest.png", "share_code"=>"www.pinterest")
Page.create("template_id"=>3, "footer_id"=>1, "parent_id"=>0, "multi_navigation_id"=>nil, "slider_id"=>nil, "position"=>0, "title"=>"Home", "navigation_text"=>"", "url_path"=>"home", "navigation_id"=>1, "published"=>true, "show_in_nav"=>true, "keywords"=>"", "description"=>"", "mobile"=>true, "redirect"=>nil, "content_status"=>nil)
Role.create("name"=>"admin")
Role.create("name"=>"editor")
Role.create("name"=>"author")
RolesUsers.create("role_id"=>1, "user_id"=>1)
RolesUsers.create("role_id"=>2, "user_id"=>1)
RolesUsers.create("role_id"=>3, "user_id"=>1)
Setting.create("analytics"=>"", "city"=>"Jenison", "email"=>"cheetahcms.gmail.com", "fax"=>"555-5555", "latitude"=>42.902493, "longitude"=>-85.80095399999999, "phone"=>"555-5555", "site_title"=>"Cheetah CMS", "state"=>"Michigan", "street"=>"100 Grandville", "tag_line"=>"Just Speed", "url"=>"www.cheetahcms.com", "zip"=>"49428")
State.create("state_name"=>"Alaska", "state_prefix"=>"AK")
State.create("state_name"=>"Alabama", "state_prefix"=>"AL")
State.create("state_name"=>"American Samoa", "state_prefix"=>"AS")
State.create("state_name"=>"Arizona", "state_prefix"=>"AZ")
State.create("state_name"=>"Arkansas", "state_prefix"=>"AR")
State.create("state_name"=>"California", "state_prefix"=>"CA")
State.create("state_name"=>"Colorado", "state_prefix"=>"CO")
State.create("state_name"=>"Connecticut", "state_prefix"=>"CT")
State.create("state_name"=>"Delaware", "state_prefix"=>"DE")
State.create("state_name"=>"District of Columbia", "state_prefix"=>"DC")
State.create("state_name"=>"Federated States of Micronesia", "state_prefix"=>"FM")
State.create("state_name"=>"Florida", "state_prefix"=>"FL")
State.create("state_name"=>"Georgia", "state_prefix"=>"GA")
State.create("state_name"=>"Guam", "state_prefix"=>"GU")
State.create("state_name"=>"Hawaii", "state_prefix"=>"HI")
State.create("state_name"=>"Idaho", "state_prefix"=>"ID")
State.create("state_name"=>"Illinois", "state_prefix"=>"IL")
State.create("state_name"=>"Indiana", "state_prefix"=>"IN")
State.create("state_name"=>"Iowa", "state_prefix"=>"IA")
State.create("state_name"=>"Kansas", "state_prefix"=>"KS")
State.create("state_name"=>"Kentucky", "state_prefix"=>"KY")
State.create("state_name"=>"Louisiana", "state_prefix"=>"LA")
State.create("state_name"=>"Maine", "state_prefix"=>"ME")
State.create("state_name"=>"Marshall Islands", "state_prefix"=>"MH")
State.create("state_name"=>"Maryland", "state_prefix"=>"MD")
State.create("state_name"=>"Massachusetts", "state_prefix"=>"MA")
State.create("state_name"=>"Michigan", "state_prefix"=>"MI")
State.create("state_name"=>"Minnesota", "state_prefix"=>"MN")
State.create("state_name"=>"Mississippi", "state_prefix"=>"MS")
State.create("state_name"=>"Missouri", "state_prefix"=>"MO")
State.create("state_name"=>"Montana", "state_prefix"=>"MT")
State.create("state_name"=>"Nebraska", "state_prefix"=>"NE")
State.create("state_name"=>"Nevada", "state_prefix"=>"NV")
State.create("state_name"=>"New Hampshire", "state_prefix"=>"NH")
State.create("state_name"=>"New Jersey", "state_prefix"=>"NJ")
State.create("state_name"=>"New Mexico", "state_prefix"=>"NM")
State.create("state_name"=>"New York", "state_prefix"=>"NY")
State.create("state_name"=>"North Carolina", "state_prefix"=>"NC")
State.create("state_name"=>"North Dakota", "state_prefix"=>"ND")
State.create("state_name"=>"Northern Mariana Islands", "state_prefix"=>"MP")
State.create("state_name"=>"Ohio", "state_prefix"=>"OH")
State.create("state_name"=>"Oklahoma", "state_prefix"=>"OK")
State.create("state_name"=>"Oregon", "state_prefix"=>"OR")
State.create("state_name"=>"Palau", "state_prefix"=>"PW")
State.create("state_name"=>"Pennsylvania", "state_prefix"=>"PA")
State.create("state_name"=>"Puerto Rico", "state_prefix"=>"PR")
State.create("state_name"=>"Rhode Island", "state_prefix"=>"RI")
State.create("state_name"=>"South Carolina", "state_prefix"=>"SC")
State.create("state_name"=>"South Dakota", "state_prefix"=>"SD")
State.create("state_name"=>"Tennessee", "state_prefix"=>"TN")
State.create("state_name"=>"Texas", "state_prefix"=>"TX")
State.create("state_name"=>"Utah", "state_prefix"=>"UT")
State.create("state_name"=>"Vermont", "state_prefix"=>"VT")
State.create("state_name"=>"Virgin Islands", "state_prefix"=>"VI")
State.create("state_name"=>"Virginia", "state_prefix"=>"VA")
State.create("state_name"=>"Washington", "state_prefix"=>"WA")
State.create("state_name"=>"West Virginia", "state_prefix"=>"WV")
State.create("state_name"=>"Wisconsin", "state_prefix"=>"WI")
State.create("state_name"=>"Wyoming", "state_prefix"=>"WY")
State.create("state_name"=>"Armed Forces Africa", "state_prefix"=>"AE")
State.create("state_name"=>"Armed Forces Americas (except Canada)", "state_prefix"=>"AA")
State.create("state_name"=>"Armed Forces Canada", "state_prefix"=>"AE")
State.create("state_name"=>"Armed Forces Europe", "state_prefix"=>"AE")
State.create("state_name"=>"Armed Forces Middle East", "state_prefix"=>"AE")
State.create("state_name"=>"Armed Forces Pacific", "state_prefix"=>"AP")
Template.create("template_name"=>"Full Width", "temp_class"=>"full-width")
Template.create("template_name"=>"Sidebar Left", "temp_class"=>"sidebar-left")
Template.create("template_name"=>"Sidebar Right", "temp_class"=>"sidebar-right")
Template.create("template_name"=>"Three Column", "temp_class"=>"three-column")
